version: "3"

services:
  front:
    build:
      context: .
      dockerfile: react-Dockerfile
    container_name: front_react
    image: react
    ports:
      - "3000:3000"
    volumes:
        - ./src/front:/app
    networks:
      - transcendence_network
    depends_on:
      - back
    
  back:
    build:
      context: .
      dockerfile: nest-Dockerfile
    container_name: back_nest
    restart: always
    ports:
      - "3001:3001"
    volumes:
      - ./src/back:/app
    networks:
      - transcendence_network
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: database
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      - transcendence_network
    volumes:
      - ./src/database:/var/run/postgresql
      - ./src/database/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    env_file:
      - .env




networks:
  transcendence_network:
    driver: bridge
