version: "3.8"

services:
  back:
    build:
      context: .
      dockerfile: nest-Dockerfile
    container_name: back_nest
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./src/back:/app
    networks:
      - transcendence_network
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: database
    restart: always
    ports: 
      - 5432:5432
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    expose: 
      - 5432
    networks:
      - transcendence_network
    volumes:
      - ./src/database:/var/run/postgresql
    env_file:
      - .env




networks:
  transcendence_network:
    driver: bridge
